clear; close all; clc;

% Load excel file
filename = 'EEG_FeatureMatrix.xlsx';
T = readtable(filename);

disp('Excel file loaded successfully.')

% Feature list
allFeatures = { ...
    'front_delta', ...
    'front_theta', ...
    'front_alpha', ...
    'front_beta', ...
    'post_delta', ...
    'post_theta', ...
    'post_alpha', ...
    'post_beta', ...
    'front_rel_theta', ...
    'front_rel_beta', ...
    'post_rel_alpha', ...
    'post_rel_theta', ...
    'theta_alpha_ratio', ...
    'slow_fast_ratio', ...
    'frontTheta_postAlpha', ...
    'PAF'};

% Function to compute stats for 1 group

computeStats = @(data) table( ...
    allFeatures', ...
    mean(data)', ...
    var(data)', ...
    std(data)', ...
    prctile(data,25)', ...
    prctile(data,50)', ...
    prctile(data,75)', ...
    'VariableNames', {'Feature','Mean','Variance','StdDev','P25','Median','P75'});

% Extract each group
AD_data  = T(strcmp(T.Group,'AD'),  allFeatures);
FTD_data = T(strcmp(T.Group,'FTD'), allFeatures);
CN_data  = T(strcmp(T.Group,'CN'),  allFeatures);


% Create three tables
AD_Table  = computeStats(table2array(AD_data));
FTD_Table = computeStats(table2array(FTD_data));
CN_Table  = computeStats(table2array(CN_data));


% Display tables
disp(' ')
disp('========== AD STATISTICS ==========')
disp(AD_Table)

disp(' ')
disp('========== FTD STATISTICS ==========')
disp(FTD_Table)

disp(' ')
disp('========== CN STATISTICS ==========')
disp(CN_Table)

% Save as excel files
writetable(AD_Table,  'AD_Statistics.xlsx');
writetable(FTD_Table, 'FTD_Statistics.xlsx');
writetable(CN_Table,  'CN_Statistics.xlsx');

disp('Three separate Excel files created.')
