clear; close all; clc;

% Load excel file
filename = 'EEG_FeatureMatrix.xlsx';
T = readtable(filename);

disp('Excel file loaded successfully.')

% Feature groupping
figure1_features = { ...
    'front_delta', ...
    'front_theta', ...
    'front_alpha', ...
    'front_beta'};
figure2_features = { ...
    'post_delta', ...
    'post_theta', ...
    'post_alpha', ...
    'post_beta'};
figure3_features = { ...
    'front_rel_theta', ...
    'front_rel_beta', ...
    'post_rel_alpha', ...
    'post_rel_theta'};
figure4_features = { ...
    'theta_alpha_ratio', ...
    'slow_fast_ratio', ...
    'frontTheta_postAlpha', ...
    'PAF'};
allFeatureGroups = {figure1_features, figure2_features, ...
                    figure3_features, figure4_features};
figureTitles = { ...
    'Frontal Absolute Powers', ...
    'Posterior Absolute Powers', ...
    'Relative Band Powers', ...
    'Band Ratios & Peak Alpha Frequency'};


% Loop through figures
for fig = 1:4

    figure('Name', figureTitles{fig});
    currentFeatures = allFeatureGroups{fig};

    for i = 1:4
        subplot(2,2,i)
        boxplot(T.(currentFeatures{i}), T.Group)
        title(currentFeatures{i}, 'Interpreter','none')
        xlabel('Group')
        ylabel('Value')
        grid on
    end

    sgtitle(figureTitles{fig})

end
